"""Configuration module for Kalshi Weather Bot."""

from kalshi_weather.config.cities import (
    CityConfig,
    NYC,
    CITIES,
    DEFAULT_CITY,
    get_city,
    list_cities,
)

from kalshi_weather.config.settings import (
    # API Endpoints
    OPEN_METEO_FORECAST_URL,
    OPEN_METEO_GFS_URL,
    OPEN_METEO_ENSEMBLE_URL,
    NWS_API_BASE,
    NWS_STATIONS_URL,
    NWS_CLIMATE_URL,
    KALSHI_API_BASE,
    KALSHI_MARKETS_URL,
    # API Settings
    API_TIMEOUT,
    NWS_USER_AGENT,
    MAX_RETRIES,
    RETRY_DELAY,
    # Trading Parameters
    MIN_EDGE_THRESHOLD,
    MAX_EDGE_THRESHOLD,
    KALSHI_FEE_RATE,
    # Forecast Parameters
    MIN_STD_DEV,
    DEFAULT_STD_DEV,
    # Display Settings
    DEFAULT_REFRESH_INTERVAL,
    CRITICAL_REEVAL_START_MINUTE,
    CRITICAL_REEVAL_END_MINUTE,
    CRITICAL_REEVAL_REFRESH_INTERVAL,
    # Auto-trading flags
    AUTO_SELL_ENABLED,
    AUTO_SELL_DRY_RUN,
    AUTO_SELL_ON_WRONG_POSITION,
    AUTO_SELL_PLACE_TARGETS,
    AUTO_SELL_MAX_CONTRACTS,
    POSITION_EXIT_FEE_RATE,
    AUTO_SELL_MIN_PROFIT_CENTS,
    AUTO_SELL_START_HOUR_LOCAL,
    AUTO_SELL_START_MINUTE_LOCAL,
    AUTO_SELL_MIN_NON_PRIMARY_CYCLES,
    AUTO_SELL_MIN_PRIMARY_GAP_PP,
    AUTO_SELL_FORCE_EXIT_HOUR_LOCAL,
    AUTO_SELL_FORCE_EXIT_MINUTE_LOCAL,
    AUTO_SELL_MIN_HOLD_MINUTES,
    AUTO_SELL_MAX_DRAWDOWN_FRACTION,
    # Logging
    LOG_LEVEL,
    LOG_FORMAT,
)

__all__ = [
    # Cities
    "CityConfig",
    "NYC",
    "CITIES",
    "DEFAULT_CITY",
    "get_city",
    "list_cities",
    # API Endpoints
    "OPEN_METEO_FORECAST_URL",
    "OPEN_METEO_GFS_URL",
    "OPEN_METEO_ENSEMBLE_URL",
    "NWS_API_BASE",
    "NWS_STATIONS_URL",
    "NWS_CLIMATE_URL",
    "KALSHI_API_BASE",
    "KALSHI_MARKETS_URL",
    # API Settings
    "API_TIMEOUT",
    "NWS_USER_AGENT",
    "MAX_RETRIES",
    "RETRY_DELAY",
    # Trading Parameters
    "MIN_EDGE_THRESHOLD",
    "MAX_EDGE_THRESHOLD",
    "KALSHI_FEE_RATE",
    # Forecast Parameters
    "MIN_STD_DEV",
    "DEFAULT_STD_DEV",
    # Display Settings
    "DEFAULT_REFRESH_INTERVAL",
    "CRITICAL_REEVAL_START_MINUTE",
    "CRITICAL_REEVAL_END_MINUTE",
    "CRITICAL_REEVAL_REFRESH_INTERVAL",
    # Auto-trading flags
    "AUTO_SELL_ENABLED",
    "AUTO_SELL_DRY_RUN",
    "AUTO_SELL_ON_WRONG_POSITION",
    "AUTO_SELL_PLACE_TARGETS",
    "AUTO_SELL_MAX_CONTRACTS",
    "POSITION_EXIT_FEE_RATE",
    "AUTO_SELL_MIN_PROFIT_CENTS",
    "AUTO_SELL_START_HOUR_LOCAL",
    "AUTO_SELL_START_MINUTE_LOCAL",
    "AUTO_SELL_MIN_NON_PRIMARY_CYCLES",
    "AUTO_SELL_MIN_PRIMARY_GAP_PP",
    "AUTO_SELL_FORCE_EXIT_HOUR_LOCAL",
    "AUTO_SELL_FORCE_EXIT_MINUTE_LOCAL",
    "AUTO_SELL_MIN_HOLD_MINUTES",
    "AUTO_SELL_MAX_DRAWDOWN_FRACTION",
    # Logging
    "LOG_LEVEL",
    "LOG_FORMAT",
]
